all: test_fork test_spawn fork spawn

test_fork: test_fork.c
	gcc -Wall -o test_fork test_fork.c

test_spawn: test_spawn.c
	gcc -Wall -o test_spawn test_spawn.c


fork: fork.c
	gcc -Wall -o fork fork.c

spawn: spawn.c
	gcc -Wall -o spawn spawn.c
